export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';
export const ACTION_LOGIN_FAIL = 'ACTION_LOGIN_FAIL';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';
export const ACTION_REGISTRATION = 'ACTION_REGISTRATION';
export const ACTION_REGISTRATION_FAIL = 'ACTION_REGISTRATION_FAIL';
export const ACTION_REGISTRATION_SUCCESS = 'ACTION_REGISTRATION_SUCCESS';
export const ACTION_LOGIN_SOCIAL = 'ACTION_LOGIN_SOCIAL';
export const ACTION_LOGIN_SOCIAL_FAIL = 'ACTION_LOGIN_SOCIAL_FAIL';
export const ACTION_LOGIN_SOCIAL_SUCCESS = 'ACTION_LOGIN_SOCIAL_SUCCESS';
export const ACTION_GET_USER_PROFILE = 'ACTION_GET_USER_PROFILE';
export const ACTION_GET_USER_PROFILE_FAIL = 'ACTION_GET_USER_PROFILE_FAIL';
export const ACTION_GET_USER_PROFILE_SUCCESS = 'ACTION_GET_USER_PROFILE_SUCCESS';

export const HOME_ACTION_GET_CATEGORIES = 'HOME_ACTION_GET_CATEGORIES';
export const HOME_ACTION_GET_CATEGORIES_SUCCESS = 'HOME_ACTION_GET_CATEGORIES_SUCCESS';
export const HOME_ACTION_GET_CATEGORIES_ERROR = 'HOME_ACTION_GET_CATEGORIES_ERROR';

export const ACTION_UPDATE_USER_PROFILE = 'ACTION_UPDATE_USER_PROFILE';
