export const ACTION_GET_OPTION_PAGE_ABOUT = 'ACTION_GET_OPTION_PAGE_ABOUT';
export const ACTION_GET_OPTION_PAGE_ABOUT_FAIL = 'ACTION_GET_OPTION_PAGE_ABOUT_FAIL';
export const ACTION_GET_OPTION_PAGE_ABOUT_SUCCESS = 'ACTION_GET_OPTION_PAGE_ABOUT_SUCCESS';

export const ACTION_GET_OPTION_PAGE_POLICY = 'ACTION_GET_OPTION_PAGE_POLICY';
export const ACTION_GET_OPTION_PAGE_POLICY_FAIL = 'ACTION_GET_OPTION_PAGE_POLICY_FAIL';
export const ACTION_GET_OPTION_PAGE_POLICY_SUCCESS = 'ACTION_GET_OPTION_PAGE_POLICY_SUCCESS';

export const ACTION_GET_OPTION_PAGE_TERMS = 'ACTION_GET_OPTION_PAGE_TERMS';
export const ACTION_GET_OPTION_PAGE_TERMS_FAIL = 'ACTION_GET_OPTION_PAGE_TERMS_FAIL';
export const ACTION_GET_OPTION_PAGE_TERMS_SUCCESS = 'ACTION_GET_OPTION_PAGE_TERMS_SUCCESS';


export const ACTION_GET_OPTION_SITE = 'ACTION_GET_OPTION_SITE';
export const ACTION_GET_OPTION_SITE_FAIL = 'ACTION_GET_OPTION_SITE_FAIL';
export const ACTION_GET_OPTION_SITE_SUCCESS = 'ACTION_GET_OPTION_SITE_SUCCESS';

export const ACTION_SEARCH = 'ACTION_SEARCH';
export const ACTION_SEARCH_FAIL = 'ACTION_SEARCH_FAIL';
export const ACTION_SEARCH_SUCCESS = 'ACTION_SEARCH_SUCCESS';
