export default [
  'js/jquery-3.5.1.min.js',
  'js/jquery-migrate-3.3.1.min.js',
  'js/mmenu.min.js',
  'js/tippy.all.min.js',
  'js/simplebar.min.js',
  'js/bootstrap-slider.min.js',
  'js/bootstrap-select.min.js',
  'js/snackbar.js',
  'js/clipboard.min.js',
  'js/counterup.min.js',
  'js/magnific-popup.min.js',
  'js/slick.min.js',
  'js/custom.js',
];