export default {
  "Log In": "Log In",
  "Register": "Register",
  "Faq": "Faq",
  "Favourite List": "Favourite List",
  "View Profile": "View Profile",
  "No data": "No data",
  "Time-sharing service makes a real impact in the future": "Time-sharing service makes a real impact in the future",
  "You can hire or be hired for any job, any time.": "You can hire or be hired for any job, any time.",
  "Popular Job Categories": "Popular Job Categories",
  "Cani": "Cani",
  "Featured Cities": "Featured Cities",
  "Create Job": "Create Job",
  "Please Login !!!": "Please Login !!!",
  "Highest Rated Freelancers": "Highest Rated Freelancers",
  "Browse All Freelancers": "Browse All Freelancers",
  "All Categories": "All Categories",
  "Nation": "Nation",
  "All Cities": "All Cities",
  "What job you want?": "What job you want?",
  "Search": "Search",
  "Jobs Posted": "Jobs Posted",
  "Freelancers": "Freelancers",
  "Message can be performed from the requester": "Message can be performed from the requester",
  "Please Register CanI first !!!": "Please Register CanI first !!!",
  "You don't have permission !!!": "You don't have permission !!!",
  "Until now": "Until now",
  "Verified": "Verified",
  "Price": "Price",
  "Content": "Content",
  "Apply Now": "Apply Now",
  "Job Summary": "Job Summary",
  "Created date": "Created date",
  "List of cani registration": "List of cani registration",
  "Rate": "Rate",
  "No registered CanI": "No registered CanI",
  "Please enter price": "Please enter price",
  "Please select service category": "Please select service category",
  "Please select your country": "Please select your country",
  "Content from 20 to 500 character": "Content from 20 to 500 character",
  "Title from 10 to 120 character": "Title from 20 to 500 character",
  "Can not change avatar": "Can not change avatar",
  "Title": "Title",
  "Currency": "Currency",
  "Image": "Image",
  "Service category": "Service category",
  "Service request description": "Service request description",
  "Post job": "Post job",
  "Create job successfully": "Create job successfully",
  "The job has been requested. Check notification information when sent by CanI candidates": "The job has been requested. Check notification information when sent by CanI candidates",
  "Confirm": "Confirm",
  "Can't chat with yourself!": "Can't chat with yourself!",
  "Have new job match with you, please check!!": "Have new job match with you, please check!!",
  "Can not load image": "Can not load image",
  "You are not registered with CanI": "You are not registered with CanI",
  "You are not registered to do this work": "You are not registered to do this work",
  "Confirm price successfully!": "Confirm price successfully!",
  "The job is not available!": "The job is not available!",
  "Delete success": "Delete success",
  "Cannot delete": "Cannot delete",
  "Anonymous": "Anonymous",
  "Sindy Forest": "Sindy Forest",
  "Job": "Job",
  "Cancel": "Cancel",
}
