export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_LOGIN_SUCCESS = 'ACTION_LOGIN_SUCCESS';
export const ACTION_LOGIN_FAIL = 'ACTION_LOGIN_FAIL';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';
export const ACTION_REGISTRATION = 'ACTION_REGISTRATION';
export const ACTION_REGISTRATION_FAIL = 'ACTION_REGISTRATION_FAIL';
export const ACTION_REGISTRATION_SUCCESS = 'ACTION_REGISTRATION_SUCCESS';
export const ACTION_LOGIN_SOCIAL = 'ACTION_LOGIN_SOCIAL';
export const ACTION_LOGIN_SOCIAL_FAIL = 'ACTION_LOGIN_SOCIAL_FAIL';
export const ACTION_LOGIN_SOCIAL_SUCCESS = 'ACTION_LOGIN_SOCIAL_SUCCESS';
export const ACTION_GET_USER_PROFILE = 'ACTION_GET_USER_PROFILE';
export const ACTION_GET_USER_PROFILE_FAIL = 'ACTION_GET_USER_PROFILE_FAIL';
export const ACTION_GET_USER_PROFILE_SUCCESS = 'ACTION_GET_USER_PROFILE_SUCCESS';

export const HOME_ACTION_GET_CATEGORIES = 'HOME_ACTION_GET_CATEGORIES';
export const HOME_ACTION_GET_CATEGORIES_SUCCESS = 'HOME_ACTION_GET_CATEGORIES_SUCCESS';
export const HOME_ACTION_GET_CATEGORIES_ERROR = 'HOME_ACTION_GET_CATEGORIES_ERROR';

export const ACTION_UPDATE_USER_PROFILE = 'ACTION_UPDATE_USER_PROFILE';
export const ACTION_UPDATE_USER_PROFILE_SUCCESS = 'ACTION_UPDATE_USER_PROFILE_SUCCESS';
export const ACTION_UPDATE_USER_PROFILE_FAIL = 'ACTION_UPDATE_USER_PROFILE_FAIL';
export const ACTION_GET_USER_PROFILE_CAN_I = 'ACTION_GET_USER_PROFILE_CAN_I';
export const ACTION_GET_USER_PROFILE_CAN_I_SUCCESS = 'ACTION_GET_USER_PROFILE_CAN_I_SUCCESS';

export const ACTION_UPDATE_USER_PROFILE_CAN_I = 'ACTION_UPDATE_USER_PROFILE_CAN_I';
export const ACTION_UPDATE_USER_PROFILE_CAN_I_SUCCESS = 'ACTION_UPDATE_USER_PROFILE_CAN_I_SUCCESS';
export const ACTION_UPDATE_USER_PROFILE_CAN_I_FAIL = 'ACTION_UPDATE_USER_PROFILE_CAN_I_FAIL';

export const ACTION_JOB_GET_DETAIL = 'ACTION_JOB_GET_DETAIL';
export const ACTION_JOB_GET_DETAIL_SUCCESS = 'ACTION_JOB_GET_DETAIL_SUCCESS';
export const ACTION_JOB_GET_DETAIL_FAIL = 'ACTION_JOB_GET_DETAIL_FAIL';

export const ACTION_JOB_POST = 'ACTION_JOB_POST';
export const ACTION_JOB_POST_SUCCESS = 'ACTION_JOB_POST_SUCCESS';
export const ACTION_JOB_POST_FAIL = 'ACTION_JOB_POST_FAIL';

export const ACTION_JOB_PICK = 'ACTION_JOB_PICK';
export const ACTION_JOB_PICK_SUCCESS = 'ACTION_JOB_PICK_SUCCESS';
export const ACTION_JOB_PICK_FAIL = 'ACTION_JOB_PICK_FAIL';

export const ACTION_MESSAGE_GET_LIST = 'ACTION_MESSAGE_GET_LIST';
export const ACTION_MESSAGE_GET_LIST_SUCCESS = 'ACTION_MESSAGE_GET_LIST_SUCCESS';
export const ACTION_MESSAGE_GET_LIST_FAIL = 'ACTION_MESSAGE_GET_LIST_FAIL';

export const ACTION_GET_USER_DETAIL = 'ACTION_GET_USER_DETAIL';
export const ACTION_GET_USER_DETAIL_SUCCESS = 'ACTION_GET_USER_DETAIL_SUCCESS';
export const ACTION_GET_USER_DETAIL_FAIL = 'ACTION_GET_USER_DETAIL_FAIL';

export const ACTION_FAVOURITE = 'ACTION_FAVOURITE';

export const ACTION_GET_FAVOURITE_LIST = 'ACTION_GET_FAVOURITE_LIST';
export const ACTION_GET_FAVOURITE_LIST_SUCCESS = 'ACTION_GET_FAVOURITE_LIST_SUCCESS';
export const ACTION_GET_FAVOURITE_LIST_FAIL = 'ACTION_GET_FAVOURITE_LIST_FAIL';

export const ACTION_GET_NOTIFICATION = 'ACTION_GET_NOTIFICATION';
export const ACTION_GET_NOTIFICATION_SUCCESS = 'ACTION_GET_NOTIFICATION_SUCCESS';
export const ACTION_GET_NOTIFICATION_LIST_FAIL = 'ACTION_GET_NOTIFICATION_LIST_FAIL';

export const ACTION_NOTIFICATION_GET_DETAIL = 'ACTION_NOTIFICATION_GET_DETAIL';
export const ACTION_NOTIFICATION_GET_DETAIL_SUCCESS = 'ACTION_NOTIFICATION_GET_DETAIL_SUCCESS';
export const ACTION_NOTIFICATION_GET_DETAIL_FAIL = 'ACTION_NOTIFICATION_GET_DETAIL_FAIL';

export const ACTION_NOTIFICATION_GET_LIST = 'ACTION_NOTIFICATION_GET_LIST';
export const ACTION_NOTIFICATION_GET_LIST_SUCCESS = 'ACTION_NOTIFICATION_GET_LIST_SUCCESS';
export const AACTION_NOTIFICATION_GET_LIST_FAIL = 'ACTION_NOTIFICATION_GET_LIST_FAIL';

export const ACTION_REVIEW_GET_LIST = 'ACTION_REVIEW_GET_LIST';
export const ACTION_REVIEW_GET_LIST_SUCCESS = 'ACTION_REVIEW_GET_LIST_SUCCESS';
export const ACTION_REVIEW_GET_LIST_FAIL = 'ACTION_REVIEW_GET_LIST_FAIL';
