const serverUrl = 'https://canui.tech';
const prefix = '';
const rootPath = `/${prefix}`;
const cmsPath = `/cms/${prefix}`;

const UrlPath = {
	Home: `${rootPath}`,
	AboutUs: `${rootPath}aboutus`,
	Services: `${rootPath}services`,
	Profile: `${rootPath}profiles`,
	CanI: `${rootPath}profiles/can-i`,
	Faq: `${rootPath}faq`,
	Privacy: `${rootPath}privacy`,
	RegisterCanI: `${rootPath}profiles/can-i`,
  JobDetail: `${rootPath}jobs`,
  Message: `${rootPath}messages`,
	Search: `${rootPath}search`,
	Support: `${rootPath}support`,
	Term: `${rootPath}terms`,
	Job: `${rootPath}job`,
  JobPost: `${rootPath}job-post`,
  UserDetail: `${rootPath}users`,
	Person: `${rootPath}person`,
	ResetPassword: `${rootPath}reset-password/:token`,
  MyPageDashboard: `${rootPath}my-page/Dashboard`,
  MyPageNotification: `${rootPath}my-page/Notification`,
  MyPageMessage: `${rootPath}my-page/Message`,
  MyPageBookmark: `${rootPath}my-page/Bookmark`,
  MyPageReview: `${rootPath}my-page/Review`,
  MyPageCouponAds: `${rootPath}my-page/CouponAds`,
  MyPageReferFriend: `${rootPath}my-page/ReferFriend`,
  MyPagePostRequest: `${rootPath}my-page/PostRequest`,
  MyPageFavourite: `${rootPath}my-page/Favourite`,
  MyPageJobsInProgress: `${rootPath}my-page/JobsInProgress`,
  MyPageJobsPosting: `${rootPath}my-page/JobsPosting`,
  MyPageJobsCompleted: `${rootPath}my-page/JobsCompleted`,
  MyPageJobsCancel: `${rootPath}my-page/JobsCancel`,
  MyPageSettings: `${rootPath}my-page/Settings`,
  MyPagePayment: `${rootPath}my-page/Payment`,
  MyPage: `${rootPath}my-page`,
  Favourite: `${rootPath}favourites`,
  Notification: `${rootPath}notification`,
  Payment: `${rootPath}payment`,
	NotFound: `${rootPath}*`,
};

const API = {
	SERVER: serverUrl,
	SIGN_UP: `${serverUrl}/api/v1/canu/signup`,
	SIGN_IN: `${serverUrl}/api/login`,
	UPLOAD_IMAGE: `${serverUrl}/api/v1/canu/uploadFile`,
  CHANGE_PASSWORD: `${serverUrl}/api/v1/canu/change-password`,
  GET_CAN_I_PROFILE: `${serverUrl}/api/v1/cani/detail`,
  GET_PROFILE: `${serverUrl}/api/v1/canu/profile`,
  UPDATE_PROFILE: `${serverUrl}/api/v1/canu/update-profile`,
  GET_USER_PROFILE: `${serverUrl}/api/v1/canu/view-profile`,
  UPDATE_CAN_I_PROFILE: `${serverUrl}/api/v1/cani/signup`,
  FORGOT_PASSWORD: `${serverUrl}/api/v1/canu/forgot-password`,
  RESET_PASSWORD: `${serverUrl}/api/v1/canu/reset-password`,
  JOB_DETAIL: `${serverUrl}/api/v1/canu/job-detail`,
  JOB_LIST: `${serverUrl}/api/v1/job/list`,
  POST_FAVOURITE: `${serverUrl}/api/v1/canu/add-favorite/`,
  GET_FAVOURITE: `${serverUrl}/api/v1/canu/get-favorite`,
  GET_CANI_REVIEW_LIST: `${serverUrl}/api/v1/job/get-rating/list`,
  GET_CANU_REVIEW_LIST: `${serverUrl}/api/v1/job/get-review/list`,
  JOB_POST: `${serverUrl}/api/v1/canu/post-job`,
  CONFIRM_PRICE: `${serverUrl}/api/v1/job/start-job`,
  PICK_JOB: `${serverUrl}/api/v1/job/pick-up`,
  GET_PARTICIPANT: `${serverUrl}/api/v1/canu/participant-list`,
  GET_CHAT_HISTORY: `${serverUrl}/api/v1/canu/show-chat`,
  DELETE_CHAT_HISTORY: `${serverUrl}/api/v1/canu/delete-chat`,
  CREATE_TRANSACTION: `${serverUrl}/api/v1/payment/get-transaction-info`,
  COMPLETE_TRANSACTION: `${serverUrl}/api/v1/canu/complete-payment`,
  GET_COUPON: `${serverUrl}/api/v1/canu/get-voucher`,
  GET_NOTIFICATION_HISTORY: `${serverUrl}/api/v1/canu/get-notification`,
  GET_NOTIFICATION_DETAIl: `${serverUrl}/api/v1/canu/get-notification-detail`,
};
const CmsPath = {
  CmsDashBoard: `${cmsPath}dashboard`,
  CmsAboutUs: `${cmsPath}aboutus`,
  CmsServices: `${cmsPath}services`,
  CmsProfile: `${cmsPath}profiles`,
  CmsCanI: `${cmsPath}profiles/can-i`,
  CmsFaq: `${cmsPath}faq`,
  CmsPrivacy: `${cmsPath}privacy`,
  CmsRegisterCanI: `${cmsPath}profiles/can-i`,
  CmsSearch: `${cmsPath}search`,
  CmsSupport: `${cmsPath}support`,
  CmsTerm: `${cmsPath}terms`,
  CmsJob: `${cmsPath}job`,
  CmsPerson: `${cmsPath}person`,
  CmsNotFound: `${cmsPath}*`,
};
export default Object.freeze({
	...UrlPath,
  API: API,
  CmsPath: CmsPath
});
